Ticket #22 Axios version update to fix high severity security warning
NCIOCPL/cgov-react-app-playground pull request #23
Opened 2021-01-07 21:02 UTC by alerosad

Closes #22

Updated axios along with listed dependencies:

npm update selfsigned --depth 2
npm update ini --depth 4
npm install axios@0.21.1
npm install --save-dev resolve-url-loader@3.1.2

2021-01-08 19:46 UTC, kate-mashkina approved these changes

2021-01-08 22:04 UTC, blairlearn requested changes
As discussed, please modify your commit comment. The preferred format is

`(#1234) Ticket title`

Obviously, replacing 1234 with the actual ticket number and Ticket title with the actual title. If there are additional details needed (e.g. an explanation of why the cucumber preprocessor was also updated), add a blank line and then put the additional text on subsequent lines.

For example:
```
(#1234) Update axios to version 0.21.1.

In addition to updating axios, updated resolve-url-loader to 
its current version. Other changes are whitespace-only. 
```

The Closes #1234 text belongs in the PR comment, not the git commit comment.

2021-02-02 15:24 UTC, alerosad commented
https://react-app-dev.cancer.gov/cgov-react-app-playground/pr-23/ @mworrest @blilianyu @lburack

2021-02-03 15:51 UTC, mworrest commented
Language toggle appears then disappears on reload of the page or flipping back and forth between Spanish and English. Otherwise looks good.

2021-02-03 17:18 UTC, alerosad commented
> Language toggle appears then disappears on reload of the page or flipping back and forth between Spanish and English. Otherwise looks good.

Yeah that happens on the current develop branch, not sure why

2021-02-04 14:56 UTC, blilianyu commented
Talking with @arcepaul, language toggle is non-issue. Passing! cc: @mworrest @lburack

2021-02-23 16:19 UTC, merged