(#48) Bump Cypress version to 10.6.0
NCIOCPL/cgov-react-app-playground pull request #68
Opened 2022-09-21 22:01 UTC by alerosad

- updated Cypress version to 10.6.0
- ran the migration helper
- added "stepDefinitions": "cypress/e2e" to package.json
- updated @cypress/code-coverage to 3.10.0

Here's a good resource to see what's changed in Cypress: https://docs.cypress.io/guides/references/migration-guide#Migrating-to-Cypress-version-10-0

But pretty much what changed when I ran the migration helper was:

- spec files were renamed to 10.0.0 format (cypress/integration -> cypress/e2e)
- filenames were changed [filename].spec.[ext] -> [filename].cy.[ext]
- cypress/support/index.js file(s) turns into -> cypress/support/e2e.js
- cypress.json turns into -> cypress.config.js

With this said, e2e testing has been configured in the project, with some minor adjustments that I had to make to get it working properly.  Besides this, the new update also allows Component testing

2022-09-22 14:32 UTC, kate-mashkina requested changes

2022-09-22 14:32 UTC, kate-mashkina commented on package.json
> +		"stepDefinitions": "cypress/e2e"
can you add another line here to specify common specs
 "commonPath":"cypress/e2e/common"

2022-09-22 14:32 UTC, kate-mashkina commented on package.json
>  		"cypress-cucumber-preprocessor": "^2.5.0",
this should be updated to  "cypress-cucumber-preprocessor": "^4.3.1"

Also, Cypress is recommending to use a different cucumber preprocessor https://github.com/badeball/cypress-cucumber-preprocessor . I think this is the one that will be supported moving forward, please discuss it with a team if we want to make a switch now

2022-10-05 17:45 UTC, sarinapadilla approved these changes
This PR loads on `react-app-dev`, so this passes for me!

2022-10-14 17:26 UTC, KateMashkinaNIH approved these changes

2022-10-17 21:18 UTC, arcepaul approved these changes

2022-10-17 21:18 UTC, merged